from . import help
from . import start
from . import anketa
from . import phoneshandlers
from . import contacthandler
from . import purchaseornot
from . import laptopshandlers
from . import householdshandlers
from . import echo
